site_name: Brisk
theme:
  name: "material"
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: light green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: light green

extra:
  search:
    language: en

  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/brisklib"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/brisklib"

copyright: "Copyright &copy; 2024 Brisk"

plugins:
  - search
  - privacy

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/brisklib/brisk
repo_name: Brisk
edit_uri: edit/main/docs/

nav:
  - Brisk:
      - index.md
      - getting_started.md
      - prerequisites.md
      - prebuilt_binaries.md
  - Modules:
      - auto/core.md
      - auto/graphics.md
      - auto/window.md
      - auto/gui.md
      - auto/widgets.md
      - auto/network.md
      - auto/internal.md
  - Reference:
      - auto/refindex.md

  - brisklib.com: https://brisklib.com
